In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import pandas as pd
import seaborn as sns

#to ignore warnings
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Path to the dataset
url = r"C:\Users\shrey\Documents\1st_Sem_Study\Projects\Accidental_Drug_Related_Deaths_CT\Accidental_Drug_Related_Deaths_2012-2022.csv"
df = pd.read_csv(url)
 
# Printing the data
first_10_rows= df.head(10)

first_10_rows.to_excel("first_10_rows_output.xlsx", index=False)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10654 entries, 0 to 10653
Data columns (total 48 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Date                           10654 non-null  object
 1   Date Type                      10654 non-null  object
 2   Age                            10652 non-null  float64
 3   Sex                            10645 non-null  object
 4   Race                           10625 non-null  object
 5   Ethnicity                      1575 non-null   object
 6   Residence City                 10148 non-null  object
 7   Residence County               9486 non-null   object
 8   Residence State                8756 non-null   object
 9   Injury City                    10476 non-null  object
 10  Injury County                  7332 non-null   object
 11  Injury State                   7741 non-null   object
 12  Injury Place                   10364 non-null  object
 13  Description of Injury          9850 non-null   object
 14  Death City                     9197 non-null   object
 15  Death County                   8090 non-null   object
 16  Death State                    6873 non-null   object
 17  Location                       10632 non-null  object
 18  Location if Other              1194 non-null   object
 19  Cause of Death                 10654 non-null  object
 20  Manner of Death                10645 non-null  object
 21  Other Significant Conditions   1010 non-null   object
 22  Heroin                         3472 non-null   object
 23  Heroin death certificate (DC)  740 non-null    object
 24  Cocaine                        3855 non-null   object
 25  Fentanyl                       6925 non-null   object
 26  Fentanyl Analogue              804 non-null    object
 27  Oxycodone                      950 non-null    object
 28  Oxymorphone                    157 non-null    object
 29  Ethanol                        2878 non-null   object
 30  Hydrocodone                    163 non-null    object
 31  Benzodiazepine                 2499 non-null   object
 32  Methadone                      938 non-null    object
 33  Meth/Amphetamine               127 non-null    object
 34  Amphet                         359 non-null    object
 35  Tramad                         284 non-null    object
 36  Hydromorphone                  67 non-null     object
 37  Morphine (Not Heroin)          55 non-null     object
 38  Xylazine                       792 non-null    object
 39  Gabapentin                     348 non-null    object
 40  Opiate NOS                     126 non-null    object
 41  Heroin/Morph/Codeine           2090 non-null   object
 42  Other Opioid                   128 non-null    object
 43  Any Opioid                     7620 non-null   object
 44  Other                          692 non-null    object
 45  ResidenceCityGeo               10488 non-null  object
 46  InjuryCityGeo                  10408 non-null  object
 47  DeathCityGeo                   10653 non-null  object
dtypes: float64(1), object(47)
memory usage: 3.9+ MB

In [4]:
df.isnull().sum()

Date                                 0
Date Type                            0
Age                                  2
Sex                                  9
Race                                29
Ethnicity                         9079
Residence City                     506
Residence County                  1168
Residence State                   1898
Injury City                        178
Injury County                     3322
Injury State                      2913
Injury Place                       290
Description of Injury              804
Death City                        1457
Death County                      2564
Death State                       3781
Location                            22
Location if Other                 9460
Cause of Death                       0
Manner of Death                      9
Other Significant Conditions      9644
Heroin                            7182
Heroin death certificate (DC)     9914
Cocaine                           6799
Fentanyl                          3729
Fentanyl Analogue                 9850
Oxycodone                         9704
Oxymorphone                      10497
Ethanol                           7776
Hydrocodone                      10491
Benzodiazepine                    8155
Methadone                         9716
Meth/Amphetamine                 10527
Amphet                           10295
Tramad                           10370
Hydromorphone                    10587
Morphine (Not Heroin)            10599
Xylazine                          9862
Gabapentin                       10306
Opiate NOS                       10528
Heroin/Morph/Codeine              8564
Other Opioid                     10526
Any Opioid                        3034
Other                             9962
ResidenceCityGeo                   166
InjuryCityGeo                      246
DeathCityGeo                         1
dtype: int64

In [5]:
# Replace blanks with 0 for numeric columns
numeric_columns = df.select_dtypes(include=np.number).columns
df[numeric_columns] = df[numeric_columns].fillna(0)

# Replace blanks with "Not given" for object (non-numeric) columns
object_columns = df.select_dtypes(exclude=np.number).columns
df[object_columns] = df[object_columns].fillna("N/A")

In [6]:
df.isnull().sum()

Date                             0
Date Type                        0
Age                              0
Sex                              0
Race                             0
Ethnicity                        0
Residence City                   0
Residence County                 0
Residence State                  0
Injury City                      0
Injury County                    0
Injury State                     0
Injury Place                     0
Description of Injury            0
Death City                       0
Death County                     0
Death State                      0
Location                         0
Location if Other                0
Cause of Death                   0
Manner of Death                  0
Other Significant Conditions     0
Heroin                           0
Heroin death certificate (DC)    0
Cocaine                          0
Fentanyl                         0
Fentanyl Analogue                0
Oxycodone                        0
Oxymorphone                      0
Ethanol                          0
Hydrocodone                      0
Benzodiazepine                   0
Methadone                        0
Meth/Amphetamine                 0
Amphet                           0
Tramad                           0
Hydromorphone                    0
Morphine (Not Heroin)            0
Xylazine                         0
Gabapentin                       0
Opiate NOS                       0
Heroin/Morph/Codeine             0
Other Opioid                     0
Any Opioid                       0
Other                            0
ResidenceCityGeo                 0
InjuryCityGeo                    0
DeathCityGeo                     0
dtype: int64

In [7]:
df['Serial Number'] = range(1, len(df) + 1)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10654 entries, 0 to 10653
Data columns (total 49 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Date                           10654 non-null  object
 1   Date Type                      10654 non-null  object
 2   Age                            10654 non-null  float64
 3   Sex                            10654 non-null  object
 4   Race                           10654 non-null  object
 5   Ethnicity                      10654 non-null  object
 6   Residence City                 10654 non-null  object
 7   Residence County               10654 non-null  object
 8   Residence State                10654 non-null  object
 9   Injury City                    10654 non-null  object
 10  Injury County                  10654 non-null  object
 11  Injury State                   10654 non-null  object
 12  Injury Place                   10654 non-null  object
 13  Description of Injury          10654 non-null  object
 14  Death City                     10654 non-null  object
 15  Death County                   10654 non-null  object
 16  Death State                    10654 non-null  object
 17  Location                       10654 non-null  object
 18  Location if Other              10654 non-null  object
 19  Cause of Death                 10654 non-null  object
 20  Manner of Death                10654 non-null  object
 21  Other Significant Conditions   10654 non-null  object
 22  Heroin                         10654 non-null  object
 23  Heroin death certificate (DC)  10654 non-null  object
 24  Cocaine                        10654 non-null  object
 25  Fentanyl                       10654 non-null  object
 26  Fentanyl Analogue              10654 non-null  object
 27  Oxycodone                      10654 non-null  object
 28  Oxymorphone                    10654 non-null  object
 29  Ethanol                        10654 non-null  object
 30  Hydrocodone                    10654 non-null  object
 31  Benzodiazepine                 10654 non-null  object
 32  Methadone                      10654 non-null  object
 33  Meth/Amphetamine               10654 non-null  object
 34  Amphet                         10654 non-null  object
 35  Tramad                         10654 non-null  object
 36  Hydromorphone                  10654 non-null  object
 37  Morphine (Not Heroin)          10654 non-null  object
 38  Xylazine                       10654 non-null  object
 39  Gabapentin                     10654 non-null  object
 40  Opiate NOS                     10654 non-null  object
 41  Heroin/Morph/Codeine           10654 non-null  object
 42  Other Opioid                   10654 non-null  object
 43  Any Opioid                     10654 non-null  object
 44  Other                          10654 non-null  object
 45  ResidenceCityGeo               10654 non-null  object
 46  InjuryCityGeo                  10654 non-null  object
 47  DeathCityGeo                   10654 non-null  object
 48  Serial Number                  10654 non-null  int64
dtypes: float64(1), int64(1), object(47)
memory usage: 4.0+ MB
None

In [8]:
df.head(5)

,Date,Date Type,Age,Sex,Race,Ethnicity,Residence City,Residence County,Residence State,Injury City,...,Gabapentin,Opiate NOS,Heroin/Morph/Codeine,Other Opioid,Any Opioid,Other,ResidenceCityGeo,InjuryCityGeo,DeathCityGeo,Serial Number
0,12/31/2022,Date of death,54.0,Male,White,N/A,OAKVILLE,LITCHFIELD,CT,WATERBURY,...,N/A,N/A,N/A,N/A,N/A,N/A,"OAKVILLE, CT\n(41.58854000000008, -73.08690999...","WATERBURY, CT\n(41.55490000000003, -73.0464699...","CT\n(41.57350273000003, -72.73830590799997)",1
1,12/31/2022,Date of death,61.0,Female,White,N/A,LEBANON,NEW LONDON,CT,WILLIMANTIC,...,N/A,N/A,N/A,N/A,Y,N/A,"LEBANON, CT\n(41.64541000000003, -72.200979999...","WILLIMANTIC, CT\n(41.71096000000006, -72.20528...","CT\n(41.57350273000003, -72.73830590799997)",2
2,12/31/2022,Date of death,54.0,Male,White,N/A,WEST HAVEN,NEW HAVEN,CT,WEST HAVEN,...,N/A,N/A,y,N/A,Y,N/A,"WEST HAVEN, CT\n(41.27228000000008, -72.949979...","WEST HAVEN, CT\n(41.27228000000008, -72.949979...","CT\n(41.57350273000003, -72.73830590799997)",3
3,12/30/2022,Date of death,48.0,Male,White,N/A,SOMERS,TOLLAND,CT,SOMERS,...,N/A,N/A,N/A,Buprenorphine,Y,Buprenorphine,"SOMERS, CT\n(41.98825000000005, -72.4401299999...","SOMERS, CT\n(41.98825000000005, -72.4401299999...","CT\n(41.57350273000003, -72.73830590799997)",4
4,12/29/2022,Date of death,41.0,Female,Black or African American,N/A,BRIDGEPORT,FAIRFIELD,CT,BRIDGEPORT,...,Y,N/A,N/A,N/A,Y,N/A,"BRIDGEPORT, CT\n(41.18213000000003, -73.190639...","BRIDGEPORT, CT\n(41.18213000000003, -73.190639...","CT\n(41.57350273000003, -72.73830590799997)",5

In [9]:
# Specify the file path where you want to save the Excel file
excel_file_path = r"C:\Users\shrey\Documents\1st_Sem_Study\Projects\Accidental_Drug_Related_Deaths_CT\New_AccidentalDeath_Datasheet.xlsx"

# Save the DataFrame to an Excel file
df.to_excel(excel_file_path, index=False)  # Set index=False to exclude the index from the Excel file

print(f"DataFrame saved to '{excel_file_path}' successfully.")

DataFrame saved to 'C:\Users\shrey\Documents\1st_Sem_Study\Projects\Accidental_Drug_Related_Deaths_CT\New_AccidentalDeath_Datasheet.xlsx' successfully.